sudo: false
language: ruby
cache: bundler
rvm:
- 2.1
before_install:
- export TZ=Europe/Oslo
script:
- bundle exec jekyll build
- script/deploy
- bundle exec htmlproof ./_site --only_4xx --href_ignore http://www.dagsavisen.no/samfunn/er-ikke-blitt-mer-enige-pa-fire-ar/,http://www.dagsavisen.no/samfunn/stortinget-glemte-rullestolstemme/,http://blog.holderdeord.no/404.html,http://www.forskning.no/artikler/2012/august/331988
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: B1CcoZEaGDUvk95bP1JaQ5itmf4mRoZoEVkT+fzCjT3gPyUKJ7//pOYYrdlOzPMIA+yFRGqCv3gvjK9+Vt+olU89eVgOpRxilnThjpMny9LvruKG4+Q/kVVZAFLaWHgF7ukfSW29jnuBlsq/QiW7RF5WY/7OIy5cE6ELwUIShBM=
notifications:
  email:
    - jari@holderdeord.no
  hipchat:
    rooms:
      secure: PHAQPD3XVi3YvNCCQTJBKYcGSXNeJF0tsLjg0OjzxBX76qHp+tL+m462mox9AIvltpR/hYtJFqswM5Xogt7Wx1w7UuLWzhYwothjyZmWy6Ap8uAW33xG3euNHgO4cryBHNEl0o+vX1p8kJpl4UlzObqGs0T2JJ3vumHpU8GPwuw=
