# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Holder de ord
tagline:          Blogg
url:              https://holderdeord.github.io/hdo-blog
paginate:         1
paginate_path:    "page/:num"
baseurl:          "/"
author:
  name:           Holder de ord
  url:            https://holderdeord.no/
  twitter:        holderdeord
  email:          mail@holderdeord.no

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/holderdeord/hdo-blog
