# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            hdo-blog
tagline:          Holder de ord sin blog
url:              https://holderdeord.github.io/hdo-blog
paginate:         1
baseurl:          /
author:
  name:           Holder de ord
  url:            https://holderdeord.no
  email:          mail@holderdeord.no

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/holderdeord/hdo-blog
