# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Holder de ord
description:      Lurer du på hva politikerne stemmer på Stortinget og lover i partiprogrammene? Følg opp dine folkevalgte her!
tagline:          Blogg
url:              http://blog.holderdeord.no
paginate:         3
paginate_path:    "page/:num"
baseurl:          "/"
author:
  name:           Holder de ord
  url:            https://www.holderdeord.no/
  twitter:        holderdeord
  email:          kontakt@holderdeord.no
collections:
  polls:
    output: true
    permalink: "/polls/:path/"

# Custom vars
markdown:         kramdown # same as github pages
version:          0.0.1
exclude: [vendor]
github:
  repo:           https://github.com/holderdeord/hdo-blog
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

