# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Holder de ord
tagline:          Blogg
url:              http://blog.holderdeord.no
paginate:         1
paginate_path:    "page/:num"
baseurl:          "/"
author:
  name:           Holder de ord
  url:            https://holderdeord.no/
  twitter:        holderdeord
  email:          kontakt@holderdeord.no
collections:
  polls:
    output: true
    permalink: "/polls/:path/"
  issues:
    output: true
    permalink: "/saker/:path/"

# Custom vars
markdown:         kramdown # same as github pages
version:          0.0.1
github:
  repo:           https://github.com/holderdeord/hdo-blog
gems:
  - jekyll-redirect-from

