# Permalinks
permalink:        pretty

# Setup
title:            Holder de ord
description:      Holder de ord er en partipolitisk uavhengig organisasjon som jobber for å gi folk større innflytelse over politikken ved hjelp av digitale verktøy.
tagline:          Blogg
url:              https://blog.holderdeord.no
paginate:         5
paginate_path:    "page/:num"
baseurl:          "/"
author:
  name:           Holder de ord
  url:            https://www.holderdeord.no/
  twitter:        holderdeord
  email:          kontakt@holderdeord.no

# Custom vars
markdown:         kramdown # same as github pages
version:          0.0.1
exclude:          [vendor, script]
github:
  repo:           https://github.com/holderdeord/hdo-blog
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

