#!/bin/bash

COMMIT=`git rev-parse HEAD`

if [[ -n "$TRAVIS_COMMIT" ]]; then
    COMMIT="$TRAVIS_COMMIT"
fi

DEPLOY_DRAFTS_COMMAND="cd /webapps/blog && git fetch origin && git checkout -f $COMMIT && bash -l -c 'bundle install --deployment && echo -e \"url: http://drafts.holderdeord.no/\nshow_drafts: true\" > _drafts_config.yml && bundle exec jekyll build --config _config.yml,_drafts_config.yml'"
DEPLOY_PROD_COMMAND="cd /webapps/blog && git fetch origin && git checkout -f $COMMIT && bash -l -c 'bundle install --deployment && bundle exec jekyll build --config _config.yml'"

if [[ -n "$HIPCHAT_API_TOKEN" ]]; then
  curl "https://api.hipchat.com/v1/rooms/message?format=json&auth_token=$HIPCHAT_API_TOKEN" \
    -d "room_id=155708&from=Deploy&message=$USER+is+deploying+hdo-blog"
fi

if [[ -n "$TRAVIS" ]]; then
  touch script/deploy_dsa && chmod 0600 script/deploy_dsa && openssl aes-256-cbc -K "$encrypted_d94cfa9a3b56_key" -iv "$encrypted_d94cfa9a3b56_iv" -in script/deploy.enc -out script/deploy_dsa -d
  ssh -o StrictHostKeyChecking=no -i script/deploy_dsa hdo@hdo01.holderdeord.no "$DEPLOY_DRAFTS_COMMAND"
  ssh -o StrictHostKeyChecking=no -i script/deploy_dsa hdo@hdo02.holderdeord.no "$DEPLOY_PROD_COMMAND"
else
  ssh hdo@hdo01.holderdeord.no "$DEPLOY_DRAFTS_COMMAND"
  ssh hdo@hdo02.holderdeord.no "$DEPLOY_PROD_COMMAND"
fi

result="$?"

if [[ -n "$HIPCHAT_API_TOKEN" ]]; then
  if [[ "$result" -eq 0 ]]; then
    curl "https://api.hipchat.com/v1/rooms/message?format=json&auth_token=$HIPCHAT_API_TOKEN" \
      -d "room_id=155708&from=Deploy&message=$USER+finished+deploying+hdo-blog&color=green"
  else
    curl "https://api.hipchat.com/v1/rooms/message?format=json&auth_token=$HIPCHAT_API_TOKEN" \
      -d "room_id=155708&from=Deploy&message=hdo-blog+deploy+failed&color=red"
  fi

fi
